<?php
// Simple placeholder generator for kantor_kpu_banten.jpg
// Requires PHP GD extension enabled (bundled with XAMPP). Run this file in browser: /assets/create_placeholder.php
$path = __DIR__ . '/kantor_kpu_banten.jpg';
$w = 1400; $h = 900;
$img = imagecreatetruecolor($w, $h);
// background gradient-like fill
$top = [240, 248, 255];
$bottom = [220, 235, 250];
for ($y = 0; $y < $h; $y++) {
    $r = (int) ($top[0] + ($bottom[0]-$top[0]) * ($y/$h));
    $g = (int) ($top[1] + ($bottom[1]-$top[1]) * ($y/$h));
    $b = (int) ($top[2] + ($bottom[2]-$top[2]) * ($y/$h));
    $col = imagecolorallocate($img, $r, $g, $b);
    imageline($img, 0, $y, $w, $y, $col);
}
// draw white rectangle
$rect_w = (int)($w * 0.6);
$rect_h = (int)($h * 0.28);
$x = (int)(($w - $rect_w) / 2);
$y = (int)(($h - $rect_h) / 2);
$white = imagecolorallocate($img, 255, 255, 255);
$shadow = imagecolorallocatealpha($img, 0, 0, 0, 80);
imagefilledrectangle($img, $x+6, $y+6, $x+$rect_w+6, $y+$rect_h+6, $shadow);
imagefilledrectangle($img, $x, $y, $x+$rect_w, $y+$rect_h, $white);
// text
$blue = imagecolorallocate($img, 11, 59, 107);
$grey = imagecolorallocate($img, 80, 100, 120);
$bold = 5; $normal = 4;
imagestring($img, $bold, $x+20, $y+18, 'Kantor KPU Provinsi Banten', $blue);
imagestring($img, $normal, $x+20, $y+62, 'Placeholder image generated by create_placeholder.php', $grey);
imagestring($img, $normal, $x+20, $y+96, date('Y-m-d H:i:s'), $grey);

// small silhouette rectangle to mimic building
$build_col = imagecolorallocate($img, 200, 220, 235);
$bx = $x + $rect_w - 220; $by = $y + 40;
imagefilledrectangle($img, $bx, $by, $bx+160, $by+120, $build_col);
for ($i=0;$i<4;$i++){
    for($j=0;$j<3;$j++){
        $winx = $bx + 12 + $i*38; $winy = $by + 12 + $j*30;
        imagefilledrectangle($img, $winx, $winy, $winx+20, $winy+16, $blue);
    }
}

// save jpeg
imagejpeg($img, $path, 90);
imagedestroy($img);

echo "Placeholder created: " . basename($path) . "\n";
echo "Path: " . $path . "\n";
echo "Open the landing page to view the image: /absensi_pegawai_kpu/";
